### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by c0sm1cdus7** [eandreani/sdk-php#10]
Buenos días.

Estoy teniendo dificultades con la API, se que este no es el canal para consultas acerca de la API, pero no encuentro otro, podrían responderme?

Consigo hacer todo con la API, realizar envíos, imprimir etiquetas, etc... Excepto conocer el estado de un envío. 

Este es el url de la consulta: https://www.e-andreani.com/eAndreaniWSStaging/Service.svc?wsdl

Este es el XML que envío:

`<?xml version="1.0" encoding="UTF-8"?>
<env:Envelope
    xmlns:env="http://www.w3.org/2003/05/soap-envelope"
    xmlns:ns1="http://www.andreani.com.ar/req"
    xmlns:ns2="http://schemas.datacontract.org/2004/07/EAndreaniWS"
    xmlns:ns3="http://www.andreani.com.ar">
    <env:Body>
        <ns3:ObtenerEstadoDistribucionCodificado>
            <ns3:EnviosConsultas>
                <ns1:CodigoCliente>CL0003750</ns1:CodigoCliente>
                <ns1:Envios>
                    <ns2:Envio>
                        <ns2:IdentificadorCliente></ns2:IdentificadorCliente>
                        <ns2:NumeroAndreani>*10000000555465</ns2:NumeroAndreani>
                    </ns2:Envio>
                </ns1:Envios>
            </ns3:EnviosConsultas>
        </ns3:ObtenerEstadoDistribucionCodificado>
    </env:Body>
</env:Envelope>
`

Y el servidor responde con el estado 404 not found, adjunto imagen de la consulta enviada via Postman.

![capture](https://user-images.githubusercontent.com/20582332/33795687-ea500b3e-dcc4-11e7-9fa0-36a8e9d95cf1.PNG)

Estoy haciendo algo mal?

Si alguien me puede apuntar en el camino correcto se lo agradecería.

Saludos,

**Comment by ebalmaceda** [comment]
Disculpame, te voy a hacer una consulta, porque no encuentro respuesta en ningun lado.
¿Como obtuviste tu usuario y contraseña para hacer el login en las apis?
Me registre en developers pero no lo veo por ningun lado.

**Comment by c0sm1cdus7** [comment]
En developers.andreani.com vas a Obtener Credenciales, si no tenés una cuenta la creas y te va a dar las credenciales de homologación de la plataforma. Una vez que estés listo para pasar a producción te pones en contacto con un agente comercial y te va a dar las credenciales de producción de tu cuenta. Cualquier cosa avisame, todos pasamos por lo mismo!

**Comment by ebalmaceda** [comment]
Muchas gracias por tu respuesta.
Si, en developer.andreani.com me da mis credenciales para homologacion, 
que son el codigo de cliente y los diferentes numeros de contraro. Con 
esto pude cotizar un envio y obtener sucursales.

Sin embargo, en esa misma pagina donde me informa mas credenciales, me 
dice "Tené en cuenta que vas a necesitar un usuario y contraseña para 
usarlas"

Y efectivamente pasa usar las APIs que aparecen en la web developers de 
Andreani me dice que tengo que hacer login con usuario:contrasela en base64.

El tema es que ese usuario y contraseña no lo tengo y no se tampoco como 
gestionarlo.

¿Sera que solamente los que ya tienen una cuenta de clientes activa 
pueden probar las apis y demas?

Muchas gracias!

Enzo E. Balmaceda
D&H Soluciones
Diseño y Desarrollo de Páginas Webs y Aplicaciones en Internet.
http://www.dyhsoluciones.com.ar/
