### ISSUE TITLE
 Uncaught Error: Class 'SoapHeader' not found 

### ISSUE THREAD

**Issue by diegolaz79** [eandreani/sdk-php#13]
Hola, recien hice la instalacion via composer, y copie el ejemplo para probar... solo agregue esta línea arriba:

`require __DIR__ . '/vendor/autoload.php';`

Pero me da el error 
```
Fatal error: Uncaught Error: Class 'SoapHeader' not found in C:\Users\.......\andreaniTest\vendor\andreani\sdk-php\src\Andreani\Resources\WsseAuthHeader.php:6
```
Falta alguna dependencia?
Gracias!

**Comment by guillebalmacedaonline** [comment]
Hola diego parece que esto esta deprecado. Pero tenes activa la extension de soap php?

**Comment by diegolaz79** [comment]
Gracias! Era eso! (una pavada que no me di cuenta :D)
