### ISSUE TITLE
usuario de prueba

### ISSUE THREAD

**Issue by gustavoghioldi** [eandreani/sdk-php#5]
Existe algún tipo de usuario de prueba sin registro solo para probar como funciona, tipo sandbox o algo por el estilo?

Saludos!

**Comment by ghost** [comment]
Hola Gustavo, ¿estás haciendo la integración para algún cliente de Andreani en particular?

**Comment by gustavoghioldi** [comment]
No, soy desarrollador y estoy probando las diferentes APIs de shipping para
un desarrollo propio.

Saludos!

2016-05-02 17:01 GMT-03:00 Grupo Logístico Andreani <
notifications@github.com>:

**Comment by ghost** [comment]
Deberías configurar el SDK en modo 'test'.
De esa manera te funcionarían estas credenciales:
User: eCommerce_Integra
Pass: passw0rd
Cliente: CL0003750
Contratos
400006710 (entrega urgente)
400006711 (entrega en sucursal)
400006709 (entrega estándar)
